# คำสั่งรับค่าข้อความจากแป้นพิมพ์โดยผู้ใช้งาน input()
# ตัวแปร varible คือ ชื่อที่ Dev. ตั้งขึ้นเองเอาไว้เก็บข้อมูลในโปรแกรม
fullname = input('ป้อนชื่อ : ')
yearborn = int(input('ป้อนปีเกิด พ.ศ. : '))
salary = input('ป้อนปีเงินเดือน : ')
print('-------------------')
print(f'ยินดีต้อนรับคุณ {fullname}')
print(f'คุณเกิดปี พ.ศ. {yearborn}')
print(f'ตอนนี้คุณอายุ {2568 - yearborn}') 
print(f'คุณได้รับเงินเดือน {salary} บาท')
print(f'คุณเสียภาษี {(float(salary) * 7 / 100):.4f} บาท')
print(f'คุณเสียภาษี {(float(salary) * 7 / 100):,.4f} บาท')